feat: 实现跳跃时挖掘的挖掘时间计算
PowerNukkitX/PowerNukkitX pull request #1064
Opened 2023-02-25 07:38 UTC by CoolLoong

2023-02-25 07:39 UTC, smartcmd approved these changes

2023-02-25 09:12 UTC, Superice666 requested changes

2023-02-25 09:12 UTC, Superice666 commented on src/main/java/cn/nukkit/block/Block.java
> +            if (player.getServer().getTick() - player.getLastInAirTick() < 6) {
需要加上注释说明这个魔数

2023-02-25 09:12 UTC, Superice666 commented on src/main/java/cn/nukkit/Player.java
> +                    //目前对于自定义方块，跳跃挖掘时客户端的显示和服务端权威方块破坏时间仍然有差异，需要继续优化下方时间计算算法
加上TODO

2023-02-25 09:12 UTC, Superice666 commented on src/main/java/cn/nukkit/Player.java
> -    long startBreakingBlockTime = 0;
目前尚未确认lastBreak与startBreakingBlockTime存在差异的原因，需要对此原因和对lastBreak更改的方式进行注释

2023-02-25 09:13 UTC, CoolLoong commented on src/main/java/cn/nukkit/block/Block.java
> +            if (player.getServer().getTick() - player.getLastInAirTick() < 6) {
debug测试出来的，一直长按跳跃，这个值不会超过5

2023-02-25 09:37 UTC, CoolLoong commented on src/main/java/cn/nukkit/Player.java
> -    long startBreakingBlockTime = 0;
现在lastBreak和startBreakingBlockTime等效了

2023-02-26 02:15 UTC, Superice666 approved these changes
开个issue记录一下未完成的细节

2023-02-26 03:18 UTC, merged