feat: 同步部分bukkit的metadata api
PowerNukkitX/PowerNukkitX pull request #1071
Opened 2023-02-28 16:24 UTC by CoolLoong

2023-03-03 15:33 UTC, Superice666 requested changes

2023-03-03 15:33 UTC, Superice666 commented on src/main/java/cn/nukkit/utils/NumberConversions.java
> +public final class NumberConversions {
一些功能跟NukkitMath重复了

2023-03-04 02:05 UTC, CoolLoong commented on src/main/java/cn/nukkit/utils/NumberConversions.java
> +public final class NumberConversions {
不太一样，方法签名和实现都不同

2023-03-04 03:18 UTC, Superice666 approved these changes
虽然不太理解为什么上次的review没有修改就被关掉了

2023-03-04 07:24 UTC, CoolLoong commented
> 虽然不太理解为什么上次的review没有修改就被关掉了

改了啊

2023-03-04 07:25 UTC, merged