Add/huskai
PowerNukkitX/PowerNukkitX pull request #1076
Opened 2023-03-05 14:05 UTC by CivicXFB

完成了尸壳的生物ai继承的僵尸
完成了尸壳攻击给予饥饿效果
完成了尸壳空闲播放的音效

2023-03-08 04:53 UTC, Superice666 requested changes

2023-03-08 04:53 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
> -    public MeleeAttackExecutor(MemoryType<? extends Entity> memory, float speed, int maxSenseRange, boolean clearDataWhenLose, int coolDown) {
建议保留此构造函数作为默认的null effect代理

2023-03-08 04:53 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/mob/EntityHusk.java
> +        Random r = new Random();
不要使用Random，会造成多线程性能下降，用ThreadLocalRandom或战利品表替代

2023-03-08 04:53 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
> +            if (!(this.effect == null)) {
为了代码风格统一，请改为使用!=

2023-03-08 04:53 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
> +            //如果这个生物没有药水效果则退出
"则退出"是一个具有歧义的迷惑性注释，通常指exit、yield或return，建议修改注释

2023-03-09 14:35 UTC, Superice666 requested changes

2023-03-09 14:37 UTC, Superice666 requested changes

2023-03-09 14:37 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
>              target.attack(ev);
没有检测事件是否被取消

2023-03-09 14:53 UTC, CivicXFB commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
>              target.attack(ev);
那个事件需要检查我有点懵

2023-03-11 13:26 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityHusk.java
> +        this.setDataProperty(new IntEntityData(Entity.DATA_AMBIENT_SOUND_INTERVAL, Entity.DATA_AMBIENT_SOUND_INTERVAL_RANGE));
setDataProperty操作建议放到initEntity下面

2023-03-12 12:57 UTC, lt-name commented on src/main/java/cn/nukkit/entity/ai/executor/MeleeAttackExecutor.java
> +            if (!ev.isCancelled()) {
重复操作
需要判断事件取消的，应该是下面的给药水等操作

2023-03-12 12:57 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityHusk.java
> +        this.setMaxHealth(20);
this.setMaxHealth(20);
this.diffHandDamage = new float[]{2.5f, 3f, 4.5f};
应当放到super.initEntity();前面

2023-03-12 12:57 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityHusk.java
> +            if (i == 0) {
感觉可以用switch

2023-03-12 12:57 UTC, lt-name commented on src/main/java/cn/nukkit/entity/passive/EntityCat.java
> +        super.initEntity();
this.setMaxHealth(10);
super.initEntity();
应当放到上面

2023-03-12 14:38 UTC, CivicXFB commented on src/main/java/cn/nukkit/entity/mob/EntityHusk.java
> +            if (i == 0) {
这怎么弄，难到我了name大佬

2023-03-13 10:56 UTC, lt-name approved these changes

2023-03-14 01:06 UTC, Superice666 approved these changes

2023-03-14 01:06 UTC, merged