凋零骷髅的ai
PowerNukkitX/PowerNukkitX pull request #1092
Opened 2023-03-15 14:36 UTC by CivicXFB

2023-03-18 13:36 UTC, Superice666 requested changes
建议实机测试下伤害是否跟wiki对应

2023-03-18 13:36 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java
> +        float r = ThreadLocalRandom.current().nextFloat(100);
1. 变量只使用了一次，可以内联
2. 8.5%可以直接生成Utils.rand(0, 200)<17，其他同理

2023-03-18 13:36 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java
> +        this.setDataProperty(new IntEntityData(Entity.DATA_AMBIENT_SOUND_EVENT_NAME, LevelSoundEventPacket.SOUND_AMBIENT));
写下注释可以吗？突然一上来会看不懂

2023-03-18 14:29 UTC, CivicXFB commented
> 

我在原版端测试过了一样的伤害

2023-03-18 14:45 UTC, CivicXFB commented on src/main/java/cn/nukkit/entity/mob/EntityWitherSkeleton.java
> +        this.setDataProperty(new IntEntityData(Entity.DATA_AMBIENT_SOUND_EVENT_NAME, LevelSoundEventPacket.SOUND_AMBIENT));
添加空闲时播放的声音

2023-03-19 03:40 UTC, Superice666 approved these changes

2023-03-19 03:40 UTC, merged