add login packet processor
PowerNukkitX/PowerNukkitX pull request #1151
Opened 2023-04-30 14:14 UTC by CoolLoong

2023-04-30 14:30 UTC, Superice666 requested changes
需要修复测试错误

2023-04-30 14:30 UTC, Superice666 commented on src/main/java/cn/nukkit/network/process/processor/LoginProcessor.java
> +        return ProtocolInfo.LOGIN_PACKET;
需要使用ProtocolInfo.toNewProtocolID(ProtocolInfo.LOGIN_PACKET)将负数存储的byte转为正常的int

2023-04-30 15:12 UTC, lt-name commented on src/main/java/cn/nukkit/network/process/processor/LoginProcessor.java
> +        server.getScheduler().scheduleAsyncTask(null, playerHandle.getPreLoginEventTask());
插件填pnx内置插件，不要填null

2023-05-01 02:09 UTC, Superice666 approved these changes

2023-05-01 02:22 UTC, lt-name commented on src/main/java/cn/nukkit/Player.java
> -                case ProtocolInfo.LOGIN_PACKET:
需要补上CLIENT_TO_SERVER_HANDSHAKE_PACKET，否则开启加密后玩家将无法完成登录

2023-05-01 02:23 UTC, lt-name commented on src/main/java/cn/nukkit/Player.java
> -                case ProtocolInfo.LOGIN_PACKET:
或者写个DataPacketProcessor

2023-05-01 03:40 UTC, merged