feat: add Skeleton AI & fix issue #1096
PowerNukkitX/PowerNukkitX pull request #1177
Opened 2023-05-09 09:57 UTC by CoolLoong

2023-05-09 10:56 UTC, Superice666 requested changes

2023-05-09 12:28 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/ai/executor/ShootExecutor.java
> +     * 近战攻击执行器
复制过来的，忘记改了，这个应该是弓箭类物品的行为

2023-05-09 12:28 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/mob/EntitySkeleton.java
> +                        new Behavior(new ShootExecutor(this::getItemInHand, CoreMemoryTypes.ATTACK_TARGET, 0.3f, 15, true, 30, 20),
空手的行为还没做

2023-05-10 11:21 UTC, smartcmd approved these changes
🥰

2023-05-10 12:50 UTC, Superice666 approved these changes

2023-05-10 15:04 UTC, merged