Update Terra
PowerNukkitX/PowerNukkitX pull request #1313
Opened 2023-07-12 13:40 UTC by smartcmd

2023-07-13 08:04 UTC, AzaleeX approved these changes

2023-07-14 02:10 UTC, SuperIceCN requested changes

2023-07-14 02:10 UTC, SuperIceCN commented on src/main/java/cn/nukkit/level/terra/TerraGenerator.java
> +            //TODO: 未知原因的 ConcurrentModificationException
这样真的好吗，报错会显著影响性能，要不还是把注释写得更详细一点，很有可能以后很长一段时间都不会再处理这个地方了

2023-07-14 02:41 UTC, smartcmd commented on src/main/java/cn/nukkit/level/terra/TerraGenerator.java
> +            //TODO: 未知原因的 ConcurrentModificationException
刚开始的时候会报这个错，后面就没有了

2023-07-14 03:31 UTC, SuperIceCN commented on src/main/java/cn/nukkit/level/terra/TerraGenerator.java
> +            //TODO: 未知原因的 ConcurrentModificationException
建议把“刚开始的时候会报这个错，后面就没有了”和一些更详细的信息写道todo旁边

2023-07-14 03:32 UTC, smartcmd commented on src/main/java/cn/nukkit/level/terra/TerraGenerator.java
> +            //TODO: 未知原因的 ConcurrentModificationException
你现在主分支也会有这个报错，这玩意不影响使用

2023-07-14 10:15 UTC, SuperIceCN commented on src/main/java/cn/nukkit/level/terra/TerraGenerator.java
> +            //TODO: 未知原因的 ConcurrentModificationException
要不先合并我再单独发个PR补充注释吧

2023-07-14 10:16 UTC, SuperIceCN approved these changes

2023-07-14 17:20 UTC, merged