feat: ability to change Minecraft version in query
PowerNukkitX/PowerNukkitX pull request #1413
Opened 2023-11-04 16:48 UTC by KoshakMineDEV

2023-11-05 06:28 UTC, BlusteryS reviewed
```java
KVdata.put("version", "v" + this.version);
```

It would be good if there was no "v" prefix when setting the custom version.

2023-11-05 12:54 UTC, SuperIceCN requested changes
LGTM

2023-11-05 12:54 UTC, SuperIceCN commented on src/main/java/cn/nukkit/event/server/QueryRegenerateEvent.java
> +    public String getVersion() {
Please add `@PowerNukkitXOnly` and `@Since` here

2023-11-05 12:54 UTC, SuperIceCN commented on src/main/java/cn/nukkit/network/RakNetInterface.java
> +                .add(dynamic(info.getVersion()))
`@PowerNukkitXDifference` here pls

2023-11-06 09:42 UTC, BlusteryS commented
the default value should contain "v" prefix

2023-11-06 12:42 UTC, KoshakMineDEV commented
> the default value should contain "v" prefix

We don't need to add it manually, because Minecraft doing it automatically. 
<img width="241" alt="image" src="https://github.com/PowerNukkitX/PowerNukkitX/assets/52908036/ea711010-46dd-414a-84a7-b96b34b8a0ec">
This is how it looks in the game with current implementation

2023-11-08 07:35 UTC, SuperIceCN approved these changes

2023-11-08 11:54 UTC, merged