fix: default DIRT_TYPE state
PowerNukkitX/PowerNukkitX pull request #1479
Opened 2024-01-29 17:49 UTC by MEFRREEX

2024-01-29 17:50 UTC, KoshakMineDEV approved these changes
LGTM

2024-01-30 02:43 UTC, smartcmd commented
This file is auto-generated

2024-01-30 02:45 UTC, CoolLoong requested changes

2024-01-30 02:45 UTC, CoolLoong commented on src/main/java/cn/nukkit/block/property/CommonBlockProperties.java
> +    EnumPropertyType<DirtType> DIRT_TYPE = EnumPropertyType.of("dirt_type", DirtType.class, DirtType.values()[1]);
Sort this enum instead of modify the index

2024-01-30 05:38 UTC, CoolLoong approved these changes

2024-01-30 08:31 UTC, merged