添加display配置项;默认生成配置文件
PowerNukkitX/PowerNukkitX pull request #184
Opened 2022-03-26 13:32 UTC by CoolLoong

2022-03-26 15:30 UTC, smartcmd commented
az

2022-03-26 16:28 UTC, CoolLoong commented
> az

这个错误是没有权限上传OSS，实际上是没问题的。本地构建成功

2022-03-27 00:13 UTC, Superice666 requested changes

2022-03-27 00:13 UTC, Superice666 commented on Bootstrap/src/main/java/cn/powernukkitx/bootstrap/Bootstrap.java
> +        if (ConfigUtils.get("display").equals("cli")) {
请修改为"cli".equals(ConfigUtils.get("display"))

2022-03-27 00:13 UTC, Superice666 commented on Bootstrap/src/main/java/cn/powernukkitx/bootstrap/Bootstrap.java
> +        if (ConfigUtils.get("display").equals("gui")) {
请修改为"gui".equals(ConfigUtils.get("display"))

2022-03-27 00:13 UTC, Superice666 commented on Bootstrap/src/main/java/cn/powernukkitx/bootstrap/util/ConfigUtils.java
> +                    Files.copy(stream, configFile.toPath());
我觉得没有必要把内置配置复制到外面去，毕竟会自动合并内外两个配置

2022-03-27 00:13 UTC, Superice666 commented on Bootstrap/src/main/resources/config.ini
> +display=cli
这里不应该有display的默认配置，这会导致无法双击启动

2022-03-27 01:44 UTC, CoolLoong commented on Bootstrap/src/main/java/cn/powernukkitx/bootstrap/util/ConfigUtils.java
> +                    Files.copy(stream, configFile.toPath());
我觉得用户可能不会第一时间看到文档，或许把配置文件直接生成会更直观一点

2022-03-27 01:55 UTC, Superice666 commented on Bootstrap/src/main/java/cn/powernukkitx/bootstrap/util/ConfigUtils.java
> +                    Files.copy(stream, configFile.toPath());
那么可以生成一个只有注释的配置文件

2022-03-27 01:55 UTC, Superice666 commented
> > az
> 
> 这个错误是没有权限上传OSS，实际上是没问题的。本地构建成功

同步下主仓库master，新的CI流程可以避免此问题

2022-03-27 04:38 UTC, CoolLoong commented
> > > az
> > 
> > 
> > 这个错误是没有权限上传OSS，实际上是没问题的。本地构建成功
> 
> 同步下主仓库master，新的CI流程可以避免此问题

我这里点击了同步但是并没有新的commit

2022-03-27 06:02 UTC, Superice666 commented
> > > > az
> > > 
> > > 
> > > 这个错误是没有权限上传OSS，实际上是没问题的。本地构建成功
> > 
> > 
> > 同步下主仓库master，新的CI流程可以避免此问题
> 
> 我这里点击了同步但是并没有新的commit

明白了，我没在pr构建中禁止上传oss，这个问题一会我解决下

2022-03-27 11:46 UTC, closed without merging