rename ender chest
PowerNukkitX/PowerNukkitX pull request #260
Opened 2022-04-25 10:26 UTC by CoolLoong

2022-04-27 14:51 UTC, Superice666 requested changes
建议改成实体事件

2022-04-28 00:53 UTC, CoolLoong commented
> 建议改成实体事件

目前只有玩家触发

2022-04-29 13:09 UTC, CoolLoong commented
> 

已修改

2022-04-29 13:11 UTC, Superice666 requested changes

2022-04-29 13:11 UTC, Superice666 commented on src/main/java/cn/nukkit/potion/Effect.java
> +        if (entity instanceof Player player) {
这使得非玩家实体仍然不会触发事件

2022-04-29 13:11 UTC, Superice666 commented on src/main/java/cn/nukkit/potion/Effect.java
>          if (entity instanceof Player) {
这使得非玩家实体仍然不会触发事件

2022-04-29 13:11 UTC, Superice666 commented on src/main/java/cn/nukkit/potion/Effect.java
> +                player.getServer().getPluginManager().callEvent(event);
Server.getInstance()

2022-04-29 13:11 UTC, Superice666 commented on src/main/java/cn/nukkit/potion/Effect.java
> +            player.getServer().getPluginManager().callEvent(event);
Server.getInstance()

2022-04-29 13:14 UTC, CoolLoong commented on src/main/java/cn/nukkit/potion/Effect.java
>          if (entity instanceof Player) {
这里是原本就有的，可能nk就是这么设计的？所以我之前只写它是Player事件

2022-04-29 13:14 UTC, CoolLoong commented on src/main/java/cn/nukkit/potion/Effect.java
> +                player.getServer().getPluginManager().callEvent(event);
我试了不加getInstance也能回调事件

2022-04-30 02:28 UTC, Superice666 approved these changes

2022-04-30 06:39 UTC, merged