New Entity AI
PowerNukkitX/PowerNukkitX pull request #431
Opened 2022-07-01 17:07 UTC by smartcmd

2022-07-02 03:32 UTC, Superice666 requested changes
而且这个架构我认为还有性能问题：
以原版猪人举例：
当一个猪人被激怒后，其余在它周围67×67×21到111×111×21区域的猪人会间隔1tick被激怒，这种间隔是目前架构难以做到的，除非我们进行时间调度，这意味着每tick都要检查一遍所有的消息和行为，况且还是在有优先级的情况下，还要保证多线程不出问题，算法难度相当于信竞压轴题，我不认为我有维护的能力。
想象一下有人要做”惊变一百天“，很可能同时运行上千个僵尸，每个僵尸有上百个行为，每tick发出几十条信息，原版的架构仍然能够轻松应对，因为理论最高时间复杂度仅仅为O(n^2)，但是你这个架构达到了O(n^n)，没法接受

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityAI.java
> +public abstract class EntityAI extends EntityPhysical{
这名字得改，`EntityAI`不应该作为一个实体的类名，反过来`AIEntity`我觉得都行

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityAI.java
> +        BehaviorGroup behaviorGroup = getBehaviorGroup();
行为的评估与执行应当分离，评估应该放在`EntityAsyncPrepare#asyncPrepare`中

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/Behavior.java
> +    protected final int priority;
JE原版代码有动态权重

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/Behavior.java
> +@Getter
少用lombok Getter，会给javadoc造成麻烦

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/Behavior.java
> +    }
缺失获取行为执行状态的方法，行为应该有三种状态，未在运行、正在运行、刚刚结束，这也是原版的做法，会给插件带来很多方便

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/BehaviorGroup.java
> +        Map<IBehavior,Position> result = evaluateBehaviors(entity, message);
`var result = ...;`

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/BehaviorGroup.java
> +        Set<IBehavior> removed = new HashSet<>();
var

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/BehaviorGroup.java
> +        Map<IBehavior,Position> evalSucceed = new HashMap<>();
var

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/IBehavior.java
> +     * @return int
不规范的JavaDoc写法

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/IBehaviorGroup.java
> +    void message(EntityAI entity, Message message);
个人认为这是个糟糕的设计，不如改成一个存储对象，由实体自己获取信息。
这个设计显然在多线程下需要大量锁，这会使得多线程性能不如单线程。

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/MultiBehavior.java
> +        Map<IBehavior,Position> result = evaluateBehaviors(entity, message);
varvar

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/MultiBehavior.java
> +        Set<Map.Entry<IBehavior, Position>> entries = result.entrySet();
var

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/MultiBehavior.java
> +        //todo: 也许我们可以加入权重系统？
权重用SortedList

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/MultiBehavior.java
> +    protected Map<IBehavior,Position> evaluateBehaviors(EntityAI entity, Message message){
应该增加只获取最高优先级行为的函数

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/MultiBehavior.java
> +        for (Map.Entry<IBehavior,Position> entry : evalSucceed.entrySet()) {
这完全就是多余的，可以改进数据结构直接完成

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/evaluator/IBehaviorEvaluator.java
> +     * @param entity
不规范的javadoc写法

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/evaluator/IBehaviorEvaluator.java
> +    Position evaluate(EntityAI entity, Message message);
不如直接返回一个record，里面可以记录各种类型的评估结果，或者干脆泛型，写死Position是个糟糕的设计，高不成低不就

2022-07-02 03:32 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/ai/message/Message.java
> +public class Message {
我个人看不懂，建议加doc

2022-07-28 08:30 UTC, Superice666 approved these changes

2022-07-28 16:09 UTC, lt-name approved these changes

2022-07-29 01:47 UTC, merged