add wolf AI
PowerNukkitX/PowerNukkitX pull request #661
Opened 2022-09-12 13:06 UTC by CoolLoong

2022-09-14 15:35 UTC, smartcmd requested changes

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/ai/executor/AboutControlExecutor.java
> +public abstract class AboutControlExecutor implements IBehaviorExecutor {
这边最好写成接口

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/Server.java
>      private int tickCounter;
Server::getTick()具有与其相同的作用

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/Player.java
> +                                    //设置PlayerAttackMemory，这里用于宠物狼的实现
能否移动到对应实体类中实现？实体狼攻击玩家攻击的目标应该是狼的一个主动的行为，写这边不是很合适
我的思路是Player类这边记录下玩家最近一次攻击的目标实体(EntityDamageByEntityEvent)，然后狼那边写个Sensor检测并将结果写入到仇恨Mem

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/Player.java
> +                                //更新wolf AttackTargetMemory记忆
同上

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/passive/EntityWolf.java
> +                            new Behavior(new EntityBreedingExecutor<>(EntitySheep.class, 16, 100, 0.35f), entity -> entity.getMemoryStorage().get(InLoveMemory.class).isInLove(), 6, 1),
EntitySheep.class没改过来

2022-09-14 15:35 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/passive/EntityWolf.java
> +                            new Behavior(new WolfLookPlayerExecutor(NearestFeedingPlayerMemory.class), new MemoryCheckNotEmptyEvaluator(NearestFeedingPlayerMemory.class), 3, 1),
这边狼应该得在看向玩家的同时移动到玩家身边吧

2022-09-14 15:36 UTC, smartcmd commented
![image](https://user-images.githubusercontent.com/60499296/190199233-88636bd3-61e3-4e6b-830a-bb5f024fcd15.png)
貌似是bug?

2022-09-14 15:39 UTC, smartcmd commented
![image](https://user-images.githubusercontent.com/60499296/190199932-dbf7ca66-172c-4985-b4fa-67a3762d98cd.png)
似乎不能正确的移动到玩家？

2022-09-14 15:49 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/passive/EntityWolf.java
> +                            new Behavior(new WolfLookPlayerExecutor(NearestFeedingPlayerMemory.class), new MemoryCheckNotEmptyEvaluator(NearestFeedingPlayerMemory.class), 3, 1),
这是没驯服的时候，不会移动，参照原版特性模仿实现

2022-09-14 15:51 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/ai/executor/AboutControlExecutor.java
> +public abstract class AboutControlExecutor implements IBehaviorExecutor {
改成接口不好封装方法，不仅仅是这四个，也为将来共有方法考虑

2022-09-14 15:59 UTC, CoolLoong commented
> ![image](https://user-images.githubusercontent.com/60499296/190199932-dbf7ca66-172c-4985-b4fa-67a3762d98cd.png) 似乎不能正确的移动到玩家？

模拟原版特性超出一定长度 大概10格才会移动

2022-09-15 04:17 UTC, CoolLoong commented on src/main/java/cn/nukkit/Player.java
> +                                    //设置PlayerAttackMemory，这里用于宠物狼的实现
已解决

2022-09-15 12:14 UTC, smartcmd approved these changes

2022-09-15 12:17 UTC, merged