Optimize the collision box calculation for arrow entity.
PowerNukkitX/PowerNukkitX pull request #757
Opened 2022-11-03 04:35 UTC by CoolLoong

2022-11-03 09:08 UTC, Superice666 requested changes

2022-11-03 09:08 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
> +            var collisionResult = this.level.fastCollisionCubes(this, currentAABB.offset(dirvec.x, dirvec.y, dirvec.z), false);
`new Vector3(dx, dy, dz).multiply(0.2 - Math.sqrt(dx * dx + dy * dy + dz * dz) * 0.01)`貌似会更好地控制箭头插入方块的深度

2022-11-03 10:17 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/projectile/EntityArrow.java
> +            var collisionResult = this.level.fastCollisionCubes(this, currentAABB.offset(dirvec.x, dirvec.y, dirvec.z), false);
部分条件下会出现箭头浮空
![image](https://user-images.githubusercontent.com/69153398/199695869-1fa1715c-538c-478b-b32b-4985c0d248dc.png)

2022-11-04 19:03 UTC, smartcmd approved these changes

2022-11-05 03:30 UTC, CoolLoong commented
@Superice666 审核一下，解决change request

2022-11-05 10:13 UTC, Superice666 approved these changes

2022-11-05 10:13 UTC, merged