Fix some issues by entity
PowerNukkitX/PowerNukkitX pull request #775
Opened 2022-11-08 14:37 UTC by SoHugePenguin

1. The problem of biological floating is serious. I simply repaired it.
2. Added the characteristics of chicken and cat.
3. This is my first contribution pnx~

2022-11-09 11:13 UTC, Superice666 requested changes
请使用IDEA自动代码格式化功能排版后再提交，感谢

2022-11-09 11:13 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if(this.motionY ==0d && this.motionX ==0d  && this.motionZ ==0d && this.onGround && this.getLevel().getBlock(new Vector3(this.x,this.y-0.001,this.z)).getId()==0){
请使用levelCachedBlock

2022-11-09 11:13 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if(this.motionY ==0d && this.motionX ==0d  && this.motionZ ==0d && this.onGround && this.getLevel().getBlock(new Vector3(this.x,this.y-0.001,this.z)).getId()==0){
~~最好避免使用魔法数字，Item.AIR更好~~
应该监测下方是否为非固体方块和流体方块

2022-11-09 12:18 UTC, Superice666 requested changes

2022-11-09 12:19 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if(this.motionY ==0d && this.motionX ==0d  && this.motionZ ==0d && this.onGround && this.getLevel().getBlock(new Vector3(this.x,this.y-0.001,this.z)).getId()==0){
你好，我思考了一下，不能单纯的检测生物脚下是不是空气，mc能穿透的不只是空气，经过研究我认为用 AxisAlignedBB 是最好的解决方案。 原来的可能在火把，活板门等能穿透方块也会造成悬浮。使用碰撞箱检测可完美解决该问题。
ps：以后会养成格式化代码习惯滴~

2022-11-09 12:32 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityBlaze.java
> +        this.setHealth(20);
我认为手动setHealth，还不如改成先setMaxHealth再调用super.initEntity()

2022-11-09 12:33 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityBlaze.java
> +        this.setHealth(20);
EntityLiving#initEntity()方法会判断nbt中是否包含生命值数据，如果不包含则读取最大生命值

2022-11-09 12:35 UTC, lt-name commented on src/main/java/cn/nukkit/entity/mob/EntityBlaze.java
> +        this.setHealth(20);
另外这样写好像会导致nk无法保存实体生命值，每次读取都强制改成满血状态了

2022-11-09 12:36 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/mob/EntityBlaze.java
> +        this.setHealth(20);
收到，我再改一下

2022-11-09 13:11 UTC, Superice666 approved these changes

2022-11-09 13:11 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if (this.onGround) {
this.needsRecalcMovement 和 this.IsImmobile() 还需要判断一下，可以大量减少没有必要的运算

2022-11-09 13:13 UTC, Superice666 requested changes

2022-11-09 13:13 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            AxisAlignedBB bb = this.boundingBox.clone();
这里应该使用offsetBoundingBox而不是永远固定在原点的BoundingBox

2022-11-09 13:24 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            this.onGround = this.level.getCollisionBlocks(bb).length > 0;
isImmobile 刚print输出无论什么情况一直是false

2022-11-09 13:26 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            this.onGround = this.level.getCollisionBlocks(bb).length > 0;
immobile
英 [ɪˈməʊbaɪl]   美 [ɪˈmoʊbl]  
adj. 不动的;静止的;不能移动的;不能活动的

2022-11-09 13:27 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            this.onGround = this.level.getCollisionBlocks(bb).length > 0;
你往下多读几行代码就明白了

2022-11-09 15:05 UTC, Superice666 requested changes

2022-11-09 15:06 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
使用碰撞箱判断会出现
![}YR)~VDFJ使用碰撞箱判断会出现
0 8K}X5UC%B5](https://user-images.githubusercontent.com/69153398/200866012-038979a9-3a10-46e2-b9e7-c6adbeb14f94.png)

2022-11-09 15:07 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
和龙哥实践了一下，还是这个好

2022-11-09 15:07 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
这个修改解决的是，当实体站在方块上，玩家打掉方块后，实体不会更新onground=false

2022-11-09 15:11 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
玩家大规模指令或插件搬家后，天上会浮空一堆生物

2022-11-09 15:17 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
判断是否站在地面上用的碰撞箱不是实体绝对位置的碰撞箱，是平面化的碰撞箱，高度为0，长宽大小略小于自身，向下偏移一点距离。
还有，即使使用只看脚下整数坐标一个方块的方法，仍然会出现如图所示的bug情况

2022-11-09 15:19 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
我认为只需要检测脚下的一格方块，检测碰撞箱有啥意义吗。还有我测试不会出现这种情况

2022-11-09 15:20 UTC, SoHugePenguin commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
实体不是很大就不会，铁傀儡肯定卡住，大部分的生物可以正常下落了，实践过了

2022-11-09 15:22 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +            if (this.getLevel().getTickCachedBlock(this.getPosition().setY(this.y - 0.001)).canPassThrough()) {
> 判断是否站在地面上用的碰撞箱不是实体绝对位置的碰撞箱，是平面化的碰撞箱，高度为0，长宽大小略小于自身，向下偏移一点距离。 还有，即使使用只看脚下整数坐标一个方块的方法，仍然会出现如图所示的bug情况

我明白了，确实是应该改为碰撞箱

2022-11-10 00:58 UTC, Superice666 approved these changes
最好能解释一下0.45 0.5 -0.6这些魔法数字.......

2022-11-10 12:16 UTC, merged