some adopt change
PowerNukkitX/PowerNukkitX pull request #799
Opened 2022-11-22 13:49 UTC by CoolLoong

2022-11-22 15:02 UTC, Superice666 requested changes

2022-11-22 15:02 UTC, Superice666 commented on src/main/java/cn/nukkit/nbt/NBTIO.java
> -        if (!tag.containsByte("Count") || !(tag.containsShort("id"))) {
Could you pls explain it futher and add `@PowerNukkitXDifference` ?

2022-11-22 15:02 UTC, Superice666 commented on src/main/java/cn/nukkit/level/format/anvil/Chunk.java
> +//        try {
Is it a debug code block?

2022-11-25 12:46 UTC, smartcmd approved these changes
没啥大问题，不过我看不出啥东西，得等冰凉来

2022-11-25 13:34 UTC, Superice666 approved these changes

2022-11-25 13:35 UTC, merged