try fix boken jvm url
PowerNukkitX/PowerNukkitX pull request #802
Opened 2022-11-23 16:19 UTC by Mr-Ao-Dragon

2022-11-25 01:57 UTC, smartcmd commented
good job！

2022-11-25 02:10 UTC, Superice666 requested changes
P.S. BootStrap已经被彻底弃用，现在应该用PNX-CLI了，新的GUI控制面板在开发中，目前的BootStrap将在开发完成后被删除

2022-11-25 02:10 UTC, Superice666 commented on .devcontainer/devcontainer.json
> +{
那个......IDE配置文件最好就先不发到主仓库了吧？

2022-12-02 14:43 UTC, CoolLoong commented
非常感谢你的PR，但是抱歉，BootStrap已经被弃用。

2022-12-02 14:43 UTC, closed without merging