新统一模组配方API
PowerNukkitX/PowerNukkitX pull request #858
Opened 2022-12-13 07:57 UTC by Superice666

2022-12-13 11:41 UTC, lt-name commented on src/main/java/cn/nukkit/inventory/CraftingManager.java
> +    public static UUID getItemWithItemDescriptorsHash(Collection<Item> items, Collection<ItemDescriptor> itemDescriptors) {
我认为应该在写个
```
@Deprecated
public static UUID getItemDescriptorsHash(Collection<Item> items, Collection<ItemDescriptor> itemDescriptors) {
return getItemWithItemDescriptorsHash(items, itemDescriptors);
}
```
防止出现插件兼容问题

2022-12-13 11:42 UTC, CoolLoong commented on src/main/java/cn/nukkit/inventory/CraftingManager.java
> +    public static UUID getItemWithItemDescriptorsHash(Collection<Item> items, Collection<ItemDescriptor> itemDescriptors) {
这个无所谓，这个是1.19.50-r2新加的

2022-12-13 11:55 UTC, CoolLoong requested changes

2022-12-13 11:55 UTC, CoolLoong commented on src/main/java/cn/nukkit/item/customitem/CustomItemDefinition.java
> +                    .putCompound("tag:" + tag, new CompoundTag());
应该与原版匹配，原版使用item_tags
`"item_tags": [],`

2022-12-13 11:55 UTC, CoolLoong commented on src/main/java/cn/nukkit/item/customitem/CustomItemDefinition.java
> +                    .putCompound("tag:" + tag, new CompoundTag());
里面是一个`ListTag<StringTag> `

2022-12-13 11:58 UTC, smartcmd approved these changes

2022-12-13 14:55 UTC, CoolLoong approved these changes

2022-12-14 06:30 UTC, CoolLoong approved these changes

2022-12-14 06:30 UTC, merged