Player Permission List
PowerNukkitX/PowerNukkitX pull request #866
Opened 2022-12-16 06:55 UTC by smartcmd

2022-12-16 15:38 UTC, Superice666 requested changes

2022-12-16 15:38 UTC, Superice666 commented on src/main/java/cn/nukkit/AdventureSettings.java
> +        if (this.playerPermission != PlayerPermission.OPERATOR && this.player.isOp())
`this.playerPermission`改成`playerPermission`吧，这个局部变量用法很奇怪

2022-12-16 15:38 UTC, Superice666 commented on src/main/java/cn/nukkit/Player.java
> +                    player.adventureSettings.setPlayerPermission(requestPermissionsPacket.permissions);
这里需要再检查一遍玩家是否在线，有挂可以在管理员退出瞬间进行回放攻击

2022-12-16 16:06 UTC, CoolLoong approved these changes

2022-12-17 02:12 UTC, Superice666 approved these changes

2022-12-17 04:42 UTC, merged