初步完成鞘翅飞行伤害计算
PowerNukkitX/PowerNukkitX pull request #897
Opened 2022-12-26 08:04 UTC by Hanmo123

#894

2022-12-27 01:58 UTC, smartcmd approved these changes

2022-12-27 07:27 UTC, Superice666 requested changes

2022-12-27 07:27 UTC, Superice666 commented on src/main/java/cn/nukkit/Player.java
> +                    if (this.isGliding() && this.speed.distance(this.speed.x, 0, this.speed.z) < 0.5 && this.getPitch() <= 40) {
`this.speed.distance(this.speed.x, 0, this.speed.z)`好像等于`Math.abs(speed.y)`，后者计算速度快得多

2022-12-28 11:16 UTC, Hanmo123 commented on src/main/java/cn/nukkit/Player.java
> +                    if (this.isGliding() && this.speed.distance(this.speed.x, 0, this.speed.z) < 0.5 && this.getPitch() <= 40) {
麻了，一下午憋了四行出来，有点头脑不清醒。

2022-12-29 02:40 UTC, Superice666 approved these changes

2022-12-29 02:40 UTC, merged