Entity AI improvement
PowerNukkitX/PowerNukkitX pull request #920
Opened 2023-01-01 07:14 UTC by smartcmd

2023-01-01 12:33 UTC, Superice666 requested changes

2023-01-01 12:54 UTC, CivicXFB commented
当前AI细节需要完善或修复:
1. 动物驯服后能在水里坐下
2. 狼在未驯服前攻击后再次驯服时出现自己打自己情况
3. 狼在未驯服前攻击不会召集同伴
4. 热带鱼没有搁浅动画
5. 狼被攻击后生气不会在玩家死亡后刷新
6. 热带鱼在接近岸边攻击上岸会发生颜色改变(我不知道什么原因)

2023-01-01 13:54 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/ai/controller/SpaceMoveController.java
> -                entity.motionX = 0;
这玩意本来增加来解决实体走钢丝的问题的，飞行实体一直可以正常停住

2023-01-09 06:01 UTC, Superice666 requested changes
还有，缺少文档

2023-01-09 06:01 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/mob/EntitySwimmingMob.java
> -            source.setCancelled(true);
为啥要去掉无视溺水伤害

2023-01-09 09:33 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        this.motionX *= factor;
可能需要某种系数

2023-01-09 12:24 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        this.motionX *= factor;
测试了下是相同的

2023-01-09 12:26 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        this.motionX *= factor;
投掷物一样的

2023-01-09 12:26 UTC, smartcmd commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        this.motionX *= factor;
压根没动

2023-01-15 01:54 UTC, closed without merging