Try to optimize hopper's performance
PowerNukkitX/PowerNukkitX pull request #943
Opened 2023-01-16 12:32 UTC by smartcmd

2023-01-18 10:54 UTC, Superice666 requested changes

2023-01-18 10:54 UTC, Superice666 commented on src/main/java/cn/nukkit/inventory/BaseInventory.java
> +    public Item getUnclonedItem(int index) {
能加上注释吗？最好加上个(创建新)注解，类似于`@DoNotModify`

2023-01-18 11:14 UTC, CoolLoong commented on src/main/java/cn/nukkit/inventory/BaseInventory.java
> +    public Item getUnclonedItem(int index) {
支持，注释编译会不显示，做个注解开发者更容易看到

2023-01-19 08:33 UTC, Superice666 approved these changes

2023-01-19 08:34 UTC, merged