fix issue#956
PowerNukkitX/PowerNukkitX pull request #957
Opened 2023-01-24 07:23 UTC by CoolLoong

2023-01-24 10:50 UTC, Superice666 requested changes

2023-01-24 10:50 UTC, Superice666 commented on src/main/java/cn/nukkit/event/player/EntityFreezeEvent.java
> +    private Entity entity;
加上final吧

2023-01-24 10:50 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if (this.getTickCachedCollisionBlocks().stream().anyMatch(block -> block.getId() == Block.POWDER_SNOW && this.getFreezingTicks() < 140)) {
1. 为什么this.getFreezingTicks() < 140要放在括号里面
2. this.getFreezingTicks() < 140完全可以提到最前面，先判断tick再判断方块碰撞以提高性能

2023-01-24 10:50 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        } else if (this.getTickCachedCollisionBlocks().stream().noneMatch(block -> block.getId() == Block.POWDER_SNOW) && this.getFreezingTicks() > 0) {
方块膨胀和上面的一次是相同的，完全可以合并

2023-01-24 10:50 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityIntelligentHuman.java
> +public class EntityIntelligentHuman extends EntityIntelligent implements HumanInventoryHolder {
这真的跟 #956 有关吗

2023-01-24 11:01 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityIntelligentHuman.java
> +public class EntityIntelligentHuman extends EntityIntelligent implements HumanInventoryHolder {
emm，这个和956无关

2023-01-24 11:35 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if (this.getTickCachedCollisionBlocks().stream().anyMatch(block -> block.getId() == Block.POWDER_SNOW && this.getFreezingTicks() < 140)) {
因为原来就是这样写的

2023-01-24 11:44 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        } else if (this.getTickCachedCollisionBlocks().stream().noneMatch(block -> block.getId() == Block.POWDER_SNOW) && this.getFreezingTicks() > 0) {
由于有对 this.getFreezingTicks() 的这个判断，所以不能移除

2023-01-24 11:44 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        if (this.getTickCachedCollisionBlocks().stream().anyMatch(block -> block.getId() == Block.POWDER_SNOW && this.getFreezingTicks() < 140)) {
已经修复

2023-01-25 05:19 UTC, Superice666 commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        } else if (this.getTickCachedCollisionBlocks().stream().noneMatch(block -> block.getId() == Block.POWDER_SNOW) && this.getFreezingTicks() > 0) {
> 由于有对 this.getFreezingTicks() 的这个判断，所以不能移除

我不太能理解这句话中的因果关系，我想这个函数应该是不会被中途挂起的吧。既然如此，为什么不做这样的更改：
```java
var collidedWithPowderSnow = this.getTickCachedCollisionBlocks().stream().anyMatch(block -> 
block.getId() == Block.POWDER_SNOW);
if (this.getFreezingTicks() < 140 && collidedWithPowderSnow) {
    this.addFreezingTicks(1);
    EntityFreezeEvent event = new EntityFreezeEvent(this);
    this.server.getPluginManager().callEvent(event);
} else if (this.getFreezingTicks() > 0 && collidedWithPowderSnow) {
    this.addFreezingTicks(-1);
}

2023-01-25 05:22 UTC, CoolLoong commented on src/main/java/cn/nukkit/entity/EntityPhysical.java
> +        } else if (this.getTickCachedCollisionBlocks().stream().noneMatch(block -> block.getId() == Block.POWDER_SNOW) && this.getFreezingTicks() > 0) {
好的我理解你的意思了

2023-01-25 13:52 UTC, Superice666 approved these changes

2023-01-25 15:21 UTC, merged