Re-implement Block.cloneTo() and remove BlockEntity.loadNBT()
PowerNukkitX/PowerNukkitX pull request #986
Opened 2023-01-29 16:07 UTC by smartcmd

2023-01-31 13:41 UTC, Superice666 requested changes
原版loadNBT也是一个必要的接口，这么大改动在给出一个合适的兼容方案前暂时没法接受

2023-01-31 13:41 UTC, Superice666 commented on src/main/java/cn/nukkit/block/BlockItemFrame.java
> +    @Since("1.6.0.0-PNX")
版本不对

2023-01-31 13:41 UTC, Superice666 commented on src/main/java/cn/nukkit/block/BlockSignPost.java
> +    @Since("1.6.0.0-PNX")
版本不对

2023-01-31 13:41 UTC, Superice666 commented on src/main/java/cn/nukkit/blockentity/BlockEntity.java
> -    @Deprecated
保留这个方法，有插件调用实现功能

2023-01-31 13:41 UTC, Superice666 commented on src/main/java/cn/nukkit/block/Block.java
> +            return BlockEntityHolder.setBlockAndCreateEntity((BlockEntityHolder<?>) clonedBlock, tryDirect, update, tag) != null;
有必要在非direct时调用loadNBT以重新恢复状态，一些插件（包括一些nkx插件）的自定义BlockEntity需要这样才能正常工作

2023-01-31 13:41 UTC, Superice666 commented on src/main/java/cn/nukkit/blockentity/BlockEntity.java
> -    @Deprecated
这并非劣质实现，只是结构有些混乱而已。
就像CUDNN上的张量乘法在计算两个整数相加时同样是非常劣质的实现一样。

2023-01-31 14:58 UTC, smartcmd commented
> 原版loadNBT也是一个必要的接口，这么大改动在给出一个合适的兼容方案前暂时没法接受

loadNBT是我加的，之前设计有问题这玩意完全没必要存在

2023-01-31 15:04 UTC, smartcmd commented on src/main/java/cn/nukkit/block/Block.java
> +            return BlockEntityHolder.setBlockAndCreateEntity((BlockEntityHolder<?>) clonedBlock, tryDirect, update, tag) != null;
那就应该覆写此方法，强制要求direct

2023-02-01 09:23 UTC, Superice666 commented
> loadNBT是我加的，之前设计有问题这玩意完全没必要存在

我已经认为没有问题并开始大量使用它了

2023-02-01 10:03 UTC, smartcmd commented
> > loadNBT是我加的，之前设计有问题这玩意完全没必要存在
> 
> 我已经认为没有问题并开始大量使用它了。
> 
> 如果你认为真的没必要的话，那就写篇文档详细说明一下方块实体的NBT到底是如何处理的吧。毕竟对于插件开发者（包括我）而言，这部分逻辑如果完全去掉loadNBT真的没法通过源代码以正常的工程思维理清楚。

可以将initEntity()关于nbt读取部分的代码独立到loadNBT()，这个我觉得是可以的

2023-02-01 11:53 UTC, Superice666 requested changes

2023-02-01 11:53 UTC, Superice666 commented on src/main/java/cn/nukkit/level/Level.java
> +     * @param direct 是否立即同步方块变更到客户端。若你进行了大量方块设置，建议将此值设置为false，然后在最后一次setBlock时设置此值为true。
不懂这个注释的意思，为什么：”在最后一次setBlock时设置此值为true“？

2023-02-01 11:54 UTC, smartcmd commented on src/main/java/cn/nukkit/level/Level.java
> +     * @param direct 是否立即同步方块变更到客户端。若你进行了大量方块设置，建议将此值设置为false，然后在最后一次setBlock时设置此值为true。
写错了，我删下

2023-02-01 12:17 UTC, merged